In [74]:
import numpy as np
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [75]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

Input Layer

In [76]:
x1 = np.array([0.1,0.2,0.2])
x2 = np.array([0.3,0.5,0.3])
x3 = np.array([0.4,0.1,0.4])

x1,x2,x3

(array([0.1, 0.2, 0.2]), array([0.3, 0.5, 0.3]), array([0.4, 0.1, 0.4]))

Weights

In [77]:
w = [0.1,0.3,0.1,0.2,0.1,-0.8,0.1,-0.2,0.3,0.4,0.1,-0.5,0.1,0.1,-0.2,0.1]

Hidden Layer

In [78]:
a1 = np.dot(x1,w[0]) + np.dot(x2,w[1]) + np.dot(x3,w[2])
sigmoid(a1)

array([0.53494295, 0.54487889, 0.53742985])

In [79]:
a2 = np.dot(x1,w[3]) + np.dot(x2,w[4]) + np.dot(x3,w[5])
sigmoid(a2)

array([0.4329071 , 0.50249998, 0.4378235 ])

In [80]:
a3 = np.dot(x1,w[6]) + np.dot(x2,w[7]) + np.dot(x3,w[8])
sigmoid(a3)

array([0.51749286, 0.4875026 , 0.51998934])

In [81]:
a4 = np.dot(x1,w[9]) + np.dot(x2,w[10]) + np.dot(x3,w[11])
sigmoid(a4)

array([0.46754569, 0.51998934, 0.47751518])

Output Layer

In [82]:
b = np.dot(sigmoid(a1),w[12]) + np.dot(sigmoid(a2),w[13]) + np.dot(sigmoid(a3),w[14]) + np.dot(sigmoid(a4),w[15])
sigmoid(b)

array([0.51000891, 0.51480475, 0.51031828])